import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import Navbar from "./components/Navbar";
import BootstrapClient from "./components/clients/BootstrapClient";
import ReactQueryClientProvider from "./components/clients/ReactQueryClient";
import { ToastContainer } from "react-toastify";
import { FavoritesProvider } from "./contexts/FavoritesContext";
import { AuthProvider } from "./contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryClientProvider>
          <AuthProvider>
            <FavoritesProvider>
              <Navbar />
              {children}
              <BootstrapClient />
            </FavoritesProvider>
            <ToastContainer />
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
